apiVersion: v1
kind: Service
metadata:
  name: svc-employeeservice
spec:
  selector:
    app: employeeservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
