custom.hikaricp.jndi-name=jdbc/EmployeeDB
custom.hikaricp.hikari.connection-timeout=5000
custom.hikaricp.hikari.idle-timeout=300000
custom.hikaricp.hikari.keepalive-time=150000
custom.hikaricp.hikari.leak-detection-threshold=60000
custom.hikaricp.hikari.max-lifetime=1800000
custom.hikaricp.hikari.maximum-pool-size=30
custom.hikaricp.hikari.minimum-idle=10
custom.hikaricp.hikari.validation-timeout=10000
custom.jpa.generate-ddl=false
custom.jpa.properties.hibernate.max_fetch_depth=3
custom.jpa.properties.hibernate.jdbc.fetch_size=100
custom.jpa.properties.hibernate.jdbc.batch_size=100
custom.jpa.properties.hibernate.order_updates=true
custom.jpa.properties.hibernate.order_inserts=true
custom.jpa.properties.hibernate.default_schema=sayantan
custom.jpa.properties.hibernate.param_null_passing=false
custom.jpa.properties.hibernate.format_sql=true
custom.jpa.properties.hibernate.show_sql=true
custom.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
custom.jpa.properties.ddl-auto=none
custom.jpa.properties.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
custom.jpa.properties.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
management.endpoints.enabled-by-default=false
management.endpoint.info.enabled=true
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=info,health
jwt.secret=EmployeeServiceSampleApplicationInGitHubPreparedBySayantanBhadra
